create table cliente (estado boolean not null, id bigint not null, contrasena varchar(255) not null, primary key (id));
create table cuenta (estado boolean not null, saldo_inicial float(53) not null, cliente_id bigint not null, cuenta_id bigint generated by default as identity, numero_cuenta varchar(255) not null, tipo_cuenta varchar(255) check (tipo_cuenta in ('Ahorro','Corriente')), primary key (cuenta_id));
create table movimiento (fecha date not null, saldo float(53) not null, valor float(53) not null, cuenta_id bigint not null, movimiento_id bigint generated by default as identity, tipo_movimiento varchar(255) not null, primary key (movimiento_id));
create table persona (edad integer not null, id bigint generated by default as identity, direccion varchar(255) not null, genero varchar(255) check (genero in ('Masculino','Femenino')), identificacion varchar(255) not null, nombre varchar(255) not null, telefono varchar(255) not null, primary key (id));
alter table if exists cliente add constraint FKkpvkbjg32bso6riqge70hwcel foreign key (id) references persona;
alter table if exists cuenta add constraint FK4p224uogyy5hmxvn8fwa2jlug foreign key (cliente_id) references cliente;
alter table if exists movimiento add constraint FK4ea11fe7p3xa1kwwmdgi9f2fi foreign key (cuenta_id) references cuenta;
