version: '3.8'

services:
  reto-tcs-ecuador:
    build: reto-tcs-ecuador
    ports:
      - "8060:8080"
    environment:
      DB_URL: jdbc:postgresql://tcs_ecuador_db:5432/tcs_ecuador?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: tcs
      DB_PASSWORD: tcs
    restart: always
    depends_on:
      tcs_ecuador_db:
        condition: service_healthy
  tcs_ecuador_db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: tcs
      POSTGRES_PASSWORD: tcs
      POSTGRES_DB: tcs_ecuador
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tcs"]
      interval: 10s
      timeout: 5s
      retries: 5
  
